---
-   name: remove Artifactory repo in favor of local mirror
    file: path=/etc/apt/sources.list.d/artifacts_artifactoryonline_com_artifacts_third_party_deps.list
        state=absent

-   name: add LOCAL fds nightly platform repo
    when: deploy_artifact == "nightly" and cluster_location is defined
    apt_repository: repo="deb http://{{cluster_location}}-apt.formationds.com/formation-apt platform nightly"
        state=present
        update_cache=yes
    tags:
      - deploy

-   name: add Artifactory fds nightly platform repo
    when: deploy_artifact == "nightly" and cluster_location is not defined
    apt_repository: repo="deb http://builder:h7qgA3fYr0P3@artifacts.artifactoryonline.com/artifacts/formation-apt/ platform nightly"
        state=present
        update_cache=yes
    tags:
      - deploy

-   name: install fds platform from repo
    when: deploy_artifact == "nightly"
    apt: name={{item}}
        force=yes
        state=present
        update_cache=yes
        default_release=platform
    with_items:
        - fds-platform
        - fds-pkghelper
        - fds-coredump
    register: fdsinstall_pkg
    tags:
      - deploy
