---
-   name: clean_node
    shell: rm -rf {{item}}
    with_items:
        - /fds/bin/*.core
        - /fds/bin/*.out
        - /fds/bin/core.*
        - /fds/bin/core
        - /fds/var/db
        - /fds/var/log/*log
        - /fds/var/logs/*log
        - /fds/var/log/*gz
        - /fds/var/logs/*gz
        - /fds/var/log/corefiles/*
        - /fds/var/stats
        - /corefiles/*
        - /fds/var/core/*.core
        - /fds/dev/hdd-*/*
        - /fds/dev/ssd-*/*
        - /fds/sys-repo/*
        - /fds/user-repo/*
        - /fds/var/redis/appendonly.aof
    tags:
        - clean

-   name: umount cores sparse file system
    mount: name=/fds/var/log/corefiles src=/fds/var/log/sfs/loopmount_sparse_file_system_for_core_files state=unmounted fstype=xfs
    when: (clean_fds is defined and clean_fds == "yes")

-   name: Remove fstab entry for cores sparse file system
    mount: name=/fds/var/log/corefiles src=/fds/var/log/sfs/loopmount_sparse_file_system_for_core_files state=absent fstype=xfs
    when: (clean_fds is defined and clean_fds == "yes")

