---
-   name: clean_node
    shell: rm -rf {{item}}
    with_items:
        - /fds/bin/*.core
        - /fds/bin/core
        - /fds/var/db
        - /fds/var/logs
        - /fds/var/stats
        - /corefiles/*.core
        - /fds/var/core/*.core
        - /fds/dev/hdd-*/*
        - /fds/dev/ssd-*/*
        - /fds/sys-repo
        - /fds/user-repo/*
    tags:
        - clean

-   name: start redis for clean
    shell: ./redis.sh start chdir=/fds/sbin
    when: fds_installed|success
    tags:
        - clean

-   name: clean redis
    shell: ./redis.sh clean chdir=/fds/sbin
    when: fds_installed|success
    tags:
        - clean

-   name: stop redis after clean
    shell: ./redis.sh stop chdir=/fds/sbin
    when: fds_installed|success
    tags:
        - clean
