---
-   name: clean_node
    shell: rm -rf {{item}}
    with_items:
        - /fds/bin/*.core
        - /fds/bin/core.*
        - /fds/bin/core
        - /fds/var/db
        - /fds/var/logs
        - /fds/var/stats
        - /corefiles/*
        - /fds/var/core/*.core
        - /fds/dev/*
        - /fds/sys-repo/*
        - /fds/user-repo/*
        - /fds/var/redis/appendonly.aof
    tags:
        - clean
