---
- include: config_sanity_check.yml

- include: stop_fds.yml

- include: clean_shared_mem.yml

- include: clean_data.yml
  when: clean_fds is defined and clean_fds == "yes"

- include: uninstall_fds.yml
  when: skip_uninstall is not defined or (skip_uninstall is defined and skip_uninstall == False)

- include: install_deps.yml

- include: ../deploy_scst/deploy_scst.yml
  when: fds_ft_am_scst_enabled == true

- include: install_fds.yml

- include: set_node_num.yml

- include: post_install_setup.yml

- include: stat_badger.yml
  when: fds_system_stats_enabled is defined and fds_system_stats_enabled == true
  tags: stat-badger

- include: start_fds.yml

- include: ../nginx/nginx_ssl_proxy.yml
  when: ssl_enabled is defined
