---
-   include: install_fds_from_repo.yml
    when: deploy_artifact is defined and deploy_artifact != "local"

-   include: install_fds_from_local.yml
    when: deploy_artifact is defined and deploy_artifact == "local"
