---
-   name: set variable build defined in inventory file (release or debug)
    set_fact:
        build: "{{ fds_build if fds_build is defined else 'debug' }}"
    tags:
      - install-local

-   name: copy local fds-platform_*{{ build }} to host
    when: deploy_artifact == "local" and this_is_an_ec2_node is not defined
    copy: src={{ item }}
      dest=/root/fds-platform.deb
    with_fileglob:
      - '../../../omnibus/omnibus-fds-platform/pkg/fds-platform_*{{ build }}*.deb'
    tags:
      - install-local

-   name: install fds platfrom from local debs
    when: deploy_artifact == "local" and this_is_an_ec2_node is not defined
    apt: deb="/root/fds-platform.deb"
    tags:
      - install-local

-   name: push local fds-platform deb from awo-bh-01 to cluster nodes
    when: deploy_artifact == "local" and (this_is_an_ec2_node is defined and this_is_an_ec2_node)
    synchronize: src="/home/deploy/deb_staging/{{ instance_name_tag }}/fds-platform.deb"
        dest="/home/deploy/fds-platform.deb"
        rsync_timeout=3 mode=push private_key="/home/deploy/.ssh/fds-deploy_rsa"
    delegate_to: awo-bh-01
    tags:
      - install-local

-   name: install fds platfrom from local debs
    when: deploy_artifact == "local" and (this_is_an_ec2_node is defined and this_is_an_ec2_node)
    apt: deb="/home/deploy/fds-platform.deb"
    tags:
      - install-local
