---
-   name: sysctl_params
    sysctl: name={{ item.key }} value={{ item.value }} state={{ item.state }}
    when: ansible_virtualization_type != "lxc"
    with_items:
        - { key: 'fs.file-max', value: '400000', state: 'present' }
        - { key: 'kernel.core_uses_pid', value: '1', state: 'present' }
        - { key: 'fs.suid_dumpable', value: '1', state: 'present' }
        - { key: 'kernel.core_pattern', value: '/corefiles/%e.%p.%u.%t.core', state: 'present' }
    tags:
        - install-deps

-   name: install_limits_conf
    template:
        src=../templates/deploy_fds/fds_limits.conf
        dest=/etc/security/limits.conf
        owner=root
        group=root
        mode=0644
    tags:
        - install-deps

-   name: ensure_corefiles_exists
    file:
        path=/corefiles
        owner=root
        group=root
        mode=0755
        state=directory
    tags:
        - install-deps

-   name: add local mirrors to /etc/hosts
    lineinfile: dest=/etc/hosts
        line="{{item}}"
    with_items:
        -   10.3.4.128 awo-apt.formationds.com awo-apt
        -   10.2.10.22 bld-apt.formationds.com bld-apt
        -   10.1.10.50 fre-apt.formationds.com fre-apt

-   name: add artifactory repo key
    apt_key: url="http://builder:h7qgA3fYr0P3@artifacts.artifactoryonline.com/artifacts/api/gpg/key/public"
    tags:
        - install-deps

-   name: add local fds nightly platform repo
    when: cluster_location is defined
    apt_repository: repo="deb http://{{cluster_location}}-apt.formationds.com/formation-apt platform nightly"
        state=present
        update_cache=yes
    tags:
      - install-deps

-   name: add Artifactory fds nightly platform repo
    when: cluster_location is not defined
    apt_repository: repo="deb http://builder:h7qgA3fYr0P3@artifacts.artifactoryonline.com/artifacts/formation-apt/ platform nightly"
        state=present
        update_cache=yes
    tags:
      - install-deps

-   name: uninstall fds-deps
    apt: name=fds-deps
        state=absent
        purge=yes
    tags:
        - uninstall

-   name: install fds-deps package
    apt: name=fds-deps
        force=yes
        state=present
        update_cache=yes
    tags:
        - install-deps
