---
-   name: install fds-stats-service deb from remote
    apt: name=fds-stats-service-2.0.0 force=yes state=latest update_cache=yes
    when: (skip_stats is not defined or skip_stats == "no") and (fds_deploy_local_deps is not defined or fds_deploy_local_deps != "yes")

-   name: install fds-stats-service-2.0.0 deb from local
    when: (skip_stats is not defined or skip_stats == "no") and (fds_deploy_local_deps is defined and fds_deploy_local_deps == "yes")
    copy: src={{ item }}
       dest="/root/fds-stats-service.deb"
    with_fileglob:
       - '../../../omnibus/omnibus-fds-stats-service/pkg/fds-stats-service*.deb'
    tags:
      - install-local

-   name: actually install the stats service
    when: (skip_stats is not defined or skip_stats == "no") and (fds_deploy_local_deps is defined and fds_deploy_local_deps == "yes")
    apt: deb="/root/fds-stats-service.deb"
    tags:
      - install-local

-   name: install rabbitmq-c deb from remote
    apt: name=rabbitmq-c-0.7.1 force=yes state=latest update_cache=yes
    when: (skip_stats is not defined or skip_stats == "no") and (fds_deploy_local_deps is not defined or fds_deploy_local_deps != "yes")

-   name: copy rabbitmq-c-0.7.1 to a local location
    when: (skip_stats is not defined or skip_stats == "no") and (fds_deploy_local_deps is defined and fds_deploy_local_deps == "yes")
    copy: src={{ item }}
      dest="/root/rabbitmq-c.deb"
    with_fileglob:
       - '../../../omnibus/omnibus-rabbitmq-c/pkg/rabbitmq-c*.deb'
    tags:
      - install-local

-   name: install the rabbitmq-c service from local
    when: (skip_stats is not defined or skip_stats == "no") and (fds_deploy_local_deps is defined and fds_deploy_local_deps == "yes")
    apt: deb="/root/rabbitmq-c.deb"
    tags:
      - install-local

-   name: install simpleamqpclient-0.7.1 deb from remote
    when: (skip_stats is not defined or skip_stats == "no") and (fds_deploy_local_deps is not defined or fds_deploy_local_deps != "yes")
    apt: name=simpleamqpclient-0.7.1 force=yes state=latest update_cache=yes

-   name: copy the simpleamqpclient-0.7.1 into the offline install
    when: (skip_stats is not defined or skip_stats == "no") and (fds_deploy_local_deps is defined and fds_deploy_local_deps == "yes")
    copy: src={{ item }}
      dest="/root/simpleamqpclient.deb"
    with_fileglob:
       - '../../../omnibus/omnibus-simpleamqpclient/pkg/simpleamqpclient*.deb'
    tags:
      - install-local

-   name: install the simpleamqpclient from local deps
    when: (skip_stats is not defined or skip_stats == "no") and (fds_deploy_local_deps is defined and fds_deploy_local_deps == "yes")
    apt: deb="/root/simpleamqpclient.deb"
    tags:
      - install-local

-   name: install the fds-stats-client-c-2.0.0 from remote
    when: (skip_stats is not defined or skip_stats == "no") and (fds_deploy_local_deps is not defined or fds_deploy_local_deps != "yes")
    apt: name=fds-stats-client-c-2.0.0 force=yes state=latest update_cache=yes

-   name: copy the fds-stats-client-c-2.0.0 into the offline install
    when: (skip_stats is not defined or skip_stats == "no") and (fds_deploy_local_deps is defined and fds_deploy_local_deps == "yes")
    copy: src={{ item }}
      dest="/root/fds-stats-client-c.deb"
    with_fileglob:
       - '../../../omnibus/omnibus-fds-stats-client-c/pkg/fds-stats-client-c*.deb'
    tags:
      - install-local

-   name: install the fds-stats-client-c-2.0.0 package from local deps
    when: (skip_stats is not defined or skip_stats == "no") and (fds_deploy_local_deps is defined and fds_deploy_local_deps == "yes")
    apt: deb="/root/fds-stats-client-c.deb"
    tags:
      - install-local
