---
-   name: sysctl_params
    sysctl: name={{ item.key }} value={{ item.value }} state={{ item.state }}
    when: ansible_virtualization_type != "lxc"
    with_items:
        - { key: 'fs.file-max', value: '400000', state: 'present' }
        - { key: 'kernel.core_uses_pid', value: '1', state: 'present' }
        - { key: 'fs.suid_dumpable', value: '1', state: 'present' }
        - { key: 'kernel.core_pattern', value: '/corefiles/%e.%p.%u.%t.core', state: 'present' }
    tags:
        - install-deps

-   name: install_limits_conf
    template:
        src=../templates/deploy_fds/fds_limits.conf
        dest=/etc/security/limits.conf
        owner=root
        group=root
        mode=0644
    tags:
        - install-deps

-   name: ensure_corefiles_exists
    file:
        path=/corefiles
        owner=root
        group=root
        mode=0755
        state=directory
    tags:
        - install-deps

-   name: ensure_os_packages_installed
    apt: name={{item}} state=present update_cache=yes
    with_items:
        - libevent-dev
        - parted
        - gdb
        - tar
        - libboost-log1.55.0
        - libboost-program-options1.55.0
        - libboost-timer1.55.0
        - libboost-thread1.55.0
        - libboost-regex1.55.0
        - libboost-date-time1.55.0
        - libleveldb-dev
        - libpcrecpp0
        - google-perftools
        - gcc
        - python-dev
        - python-pycurl
    tags:
        - install-deps

-   name: add local mirrors to /etc/hosts
    lineinfile: dest=/etc/hosts
        line="{{item}}"
    with_items:
        -   10.3.4.128 awo-apt.formationds.com awo-apt
        -   10.2.10.22 bld-apt.formationds.com bld-apt
        -   10.1.10.50 fre-apt.formationds.com fre-apt

-   name: add artifactory repo key
    apt_key: url="http://builder:h7qgA3fYr0P3@artifacts.artifactoryonline.com/artifacts/api/gpg/key/public"
    tags:
        - install-deps

-   name: add LOCAL mirror for third party packages
    apt_repository: repo="deb http://{{cluster_location}}-apt.formationds.com/third-party-deps/ fds main"
        state=present
        update_cache=yes
    when: cluster_location is defined
    tags:
        - install-deps

-   name: add Artifactory repo for third party packages
    apt_repository: repo="deb http://builder:h7qgA3fYr0P3@artifacts.artifactoryonline.com/artifacts/third-party-deps/ fds main"
        state=present
        update_cache=yes
    when: cluster_location is not defined
    tags:
        - install-deps

-   name: install third party deps from artifactory repo
    apt: name={{item}}
        force=yes
        state=present
        update_cache=yes
        default_release=fds
    with_items:
        - libpcre3
        - "libconfig++9"
        - libev4
        - libreadline5
        - libcryptopp-dev
        - xfsprogs
        - libjemalloc1
        - redis-tools
        - redis-server
        - java-common
        - oracle-java8-jdk
        - libical1
        - libhiredis0.10
        - python-setuptools
        - python-colorama
        - python-distlib
        - python-html5lib
        - python-pip
    tags:
        - install-deps

-   name: install needed pip modules
    pip: name={{item.name}} version={{item.version}}
    with_items:
        - { name: 'paramiko', version: '1.15.1' }
        - { name: 'scp', version: '0.8.0' }
        - { name: 'boto', version: '2.34.0' }
    tags:
        - install-deps
