---
-   name: set varaible build defined in inventory file (release or debug)
    set_fact:
        build: "{{ fds_build if fds_build is defined else 'debug' }}"

-   name: copy local fds-platform-{{ build }} to host
    when: deploy_artifact == "local"
    copy: src={{ item }}
      dest=/root/fds-platform.deb
    with_fileglob:
      - '../../../source/tools/install/pkg-{{ build }}/fds-platform-{{ build }}*.deb'
    tags:
      - install-local

-   name: install fds platfrom from local debs
    when: deploy_artifact == "local"
    apt: deb="/root/fds-platform.deb"
    tags:
      - install-local

-   name: delete local debs from /root/ to avoid conflicts
    when: deploy_artifact == "local"
    file: path=/root/{{ item }}
        state=absent
    with_fileglob:
      - 'fds-*.deb'
    tags:
      - install-local
