---
-   name: remove local 3rd party repo in favor of Artifactory
    file: path=/etc/apt/sources.list.d/{{item}}-apt_formationds_com_third_party_deps.list
        state=absent
    with_items:
        - awo
        - bld
        - fre
    tags:
      - install-repo

-   name: remove local formation repo in favor of Artifactory
    file: path=/etc/apt/sources.list.d/{{item}}-apt_formationds_com_formation_apt.list
        state=absent
    with_items:
        - awo
        - bld
        - fre
    tags:
      - install-repo

-   name: add Artifactory fds nightly platform repo
    when: deploy_artifact == "nightly" or deploy_artifact == "beta"
    apt_repository: repo="deb http://builder:h7qgA3fYr0P3@artifacts.artifactoryonline.com/artifacts/formation-apt/ platform {{deploy_artifact}}"
        state=present
        update_cache=yes
    tags:
      - install-repo

-   name: install fds platform from repo
    when: (deploy_artifact == "nightly" or deploy_artifact == "beta")
    apt: name=fds-platform-{{ build }}
        force=yes
        state=present
        update_cache=yes
        default_release=platform
    register: fdsinstall_pkg
    tags:
      - install-repo
