---
-   name: sysctl_params
    sysctl: name={{ item.key }} value={{ item.value }} state={{ item.state }}
    when: ansible_virtualization_type != "lxc"
    with_items:
        - { key: 'fs.file-max', value: '400000', state: 'present' }
        - { key: 'kernel.core_uses_pid', value: '1', state: 'present' }
        - { key: 'fs.suid_dumpable', value: '1', state: 'present' }
        - { key: 'kernel.core_pattern', value: '/corefiles/%e.%p.%u.%t.core', state: 'present' }
    tags:
        - install-deps

-   name: install_limits_conf
    template:
        src=../templates/deploy_fds/fds_limits.conf
        dest=/etc/security/limits.conf
        owner=root
        group=root
        mode=0644
    tags:
        - install-deps

-   name: ensure_corefiles_exists
    file:
        path=/corefiles
        owner=root
        group=root
        mode=0755
        state=directory
    tags:
        - install-deps

-   name: add local mirrors to /etc/hosts
    lineinfile: dest=/etc/hosts
        line="{{item}}"
    with_items:
        -   10.3.4.128 awo-apt.formationds.com awo-apt
        -   10.2.10.22 bld-apt.formationds.com bld-apt
        -   10.1.10.50 fre-apt.formationds.com fre-apt

-   name: add artifactory repo key
    apt_key: url="http://builder:h7qgA3fYr0P3@artifacts.artifactoryonline.com/artifacts/api/gpg/key/public"
    tags:
        - install-deps

-   name: add LOCAL mirror for third party packages
    apt_repository: repo="deb http://{{cluster_location}}-apt.formationds.com/third-party-deps/ fds main"
        state=present
        update_cache=yes
    when: cluster_location is defined
    tags:
        - install-deps

-   name: add LOCAL fds nightly platform repo
    when: deploy_artifact == "nightly" and cluster_location is defined
    apt_repository: repo="deb http://{{cluster_location}}-apt.formationds.com/formation-apt platform nightly"
        state=present
        update_cache=yes
    tags:
      - install-deps

-   name: add Artifactory fds nightly platform repo
    when: deploy_artifact == "nightly" and cluster_location is not defined
    apt_repository: repo="deb http://builder:h7qgA3fYr0P3@artifacts.artifactoryonline.com/artifacts/formation-apt/ platform nightly"
        state=present
        update_cache=yes
    tags:
      - install-deps

-   name: add Artifactory repo for third party packages
    apt_repository: repo="deb http://builder:h7qgA3fYr0P3@artifacts.artifactoryonline.com/artifacts/third-party-deps/ fds main"
        state=present
        update_cache=yes
    when: cluster_location is not defined
    tags:
        - install-deps

-   name: install third party deps from artifactory repo
    apt: name={{item}}
        force=yes
        state=present
        update_cache=yes
        default_release=fds
    with_items:
        - oracle-java8-jdk
    tags:
        - install-deps

-   name: uninstall fds-deps
    apt: name=fds-deps
        state=absent
        purge=yes
    tags:
        - uninstall

-   name: install fds-deps package
    apt: name=fds-deps
        force=yes
        state=present
        update_cache=yes
    when: deploy_artifact == 'nightly'
    tags:
        - install-deps

-   name: copy local fds-deps.deb to host
    when: deploy_artifact == "local"
    copy: src={{ item }}
      dest=/root/fds-deps.deb
    with_fileglob:
      - '../../playbooks/resources/fds-deps_*.deb'
    when: deploy_artifact == 'local'
    tags:
      - install-local

-   name: install fds deps from local debs
    apt: deb="/root/fds-deps.deb"
    when: deploy_artifact == "local"
    tags:
      - install-local

-   name: delete local debs from /root/ to avoid conflict
    file: path=/root/{{ item }}
        state=absent
    with_fileglob:
      - 'fds-deps.deb'
    when: deploy_artifact == "local"
    tags:
      - install-local
