---
-   name: copy fdsinstall.py to /root/fdsinstally.py
    copy: src=../../../source/tools/install/fdsinstall.py
        dest=/root/fdsinstall.py
        mode=0755
    when: fds_ft_platform_use_new_superblock is not defined or fds_ft_platform_use_new_superblock == "false"
    tags:
        - post-install

# This being in /root is legacy and should probably get removed once
# fdsinstall is no longer referencing disk_type.py here
-   name: copy disk_type.py to /root/disk_type.py
    copy: src=../../../source/platform/python/disk_type.py
        dest=/root/disk_type.py
        mode=0755
    when: fds_ft_platform_use_new_superblock is not defined or fds_ft_platform_use_new_superblock == "false"
    tags:
        - post-install

-   name: run fdsinstall step 3 - setup storage
    environment:
        PATH: /opt/fds-deps/embedded/sbin:{{ ansible_env.PATH }}
    shell: ./fdsinstall.py -o 5 -o 3  chdir=/root
    when: (clean_fds is defined and clean_fds == "yes") and (force is defined and force == "yes") and (fds_ft_enable_disk_activation is not defined or fds_ft_enable_disk_activation == "false") and (fds_ft_platform_use_new_superblock is not defined or fds_ft_platform_use_new_superblock == "false")
    tags:
        - post-install

-   name: manual selection and format disks
    pause: prompt="please select and format disks using [/fds/bin/fds-disk --select] and format [/fds/bin/fds-disk --format]"
    when: (clean_fds is defined and clean_fds == "yes") and (force is defined and force == "yes") and (fds_ft_enable_disk_activation is defined and fds_ft_enable_disk_activation == "true") and (fds_ft_platform_use_new_superblock is not defined or fds_ft_platform_use_new_superblock == "false")
    tags:
        - post-install

-   name: manual disk identification
    pause: prompt="Please execute disk_id.py on each node in your cluster, then return here and press enter to continue the deployment process..."
    when: (clean_fds is defined and clean_fds == "yes") and (force is defined and force == "yes") and (fds_ft_platform_use_new_superblock is defined ) and (fds_ft_platform_use_new_superblock == "true") and auto_disk_id is not defined
    tags:
        - post-install

-   name: Automatic disk identification
    command: /fds/bin/disk_id.py -wv
    when: (clean_fds is defined and clean_fds == "yes") and (force is defined and force == "yes") and (fds_ft_platform_use_new_superblock is defined ) and (fds_ft_platform_use_new_superblock == "true") and auto_disk_id is defined
    tags:
        - post-install

-   name: Formatting disks for use by Formation One
    command: /fds/bin/disk_format.py --format --reset
    when: (clean_fds is defined and clean_fds == "yes") and (force is defined and force == "yes") and (fds_ft_platform_use_new_superblock is defined ) and (fds_ft_platform_use_new_superblock == "true")
    tags:
        - post-install


-   name: render /fds/etc config files
    template:
        src=../../source/config/etc/{{item}}.conf.j2
        dest=/fds/etc/{{item}}.conf
        owner=root
        group=root
        mode=0644
    with_items:
        - fds
        - platform
        - redis
    tags:
        - post-install
        - fdsconfig

-   name: render /fds/etc/formation_env config file
    template:
        src=../../source/config/etc/formation_env.j2
        dest=/fds/etc/formation_env
        owner=root
        group=root
        mode=0754
    tags:
        - post-install

-   name: render /fds/etc/log4j2.xml config file
    template:
        src=../../source/config/etc/log4j2.xml.j2
        dest=/fds/etc/log4j2.xml
        owner=root
        group=root
        mode=0754
    tags:
        - post-install

-   name: setup influxdb user and group
    group: name=influxdb
    tags:
        - post-install
        - influxdb

-   user: name=influxdb
        createhome=no
        group=influxdb
    tags:
        - post-install
        - influxdb

-   name: render influxdb config
    template:
        src=../templates/deploy_fds/influxdb_config.toml.j2
        dest=/fds/etc/influxdb_config.toml
        owner=influxdb
        group=influxdb
        mode=0644
    tags:
        - post-install
        - influxdb

-   name: copy influxdb init script
    template:
        src=../templates/deploy_fds/influxdb_init.sh.j2
        dest=/etc/init.d/influxdb
        owner=root
        group=root
        mode=0744
    tags:
        - post-install
        - init
        - influxdb

-   name: create influxdb log/data dir
    file:
        path=/opt/influxdb/shared
        state=directory
        owner=influxdb
        group=root
        mode=0755
    tags:
        - post-install
        - influxdb

-   name: put upstart configs in place
    template:
        src=../templates/deploy_fds/upstart/fds-{{item}}.conf.j2
        dest=/etc/init/fds-{{item}}.conf
        owner=root
        group=root
        mode=0644
    with_items:
        - om
        - am
        - bare_am
        - sm
        - dm
        - pm
        - redis
        - influxdb

    tags:
        - post-install
        - init

-   name: put upstart configs in place (old superblock location only)
    template:
        src=../templates/deploy_fds/upstart/fds-{{item}}.conf.j2
        dest=/etc/init/fds-{{item}}.conf
        owner=root
        group=root
        mode=0644
    when: fds_ft_platform_use_new_superblock is not defined
    with_items:
        - disktype
    tags:
        - post-install
        - init
