---
-   name: copy fdsinstall.py to /root/fdsinstally.py
    copy: src=../../../source/tools/install/fdsinstall.py
        dest=/root/fdsinstall.py
        mode=0755
    tags:
        - post-install

-   name: copy disk_type.py to /root/disk_type.py
    copy: src=../../../source/platform/python/disk_type.py
        dest=/root/disk_type.py
        mode=0755
    tags:
        - post-install

-   name: run fdsinstall step 3 - setup storage
    shell: ./fdsinstall.py -o 5 -o 3  chdir=/root
    when: (clean_fds is defined and clean_fds == "yes") and (force is defined and force == "yes")
    tags:
        - post-install

-   name: render deploy_formation.conf
    template:
        src=../../source/test/formation.conf.j2
        dest=/fds/sbin/deploy_formation.conf
        owner=root
        group=root
        mode=0644
    tags:
        - post-install
        - fdsconfig

-   name: render /fds/etc config files
    template:
        src=../../source/config/etc/{{item}}.conf.j2
        dest=/fds/etc/{{item}}.conf
        owner=root
        group=root
        mode=0644
    with_items:
        - fds
        - fds-features
        - platform
        - orch_mgr
        - redis
    tags:
        - post-install
        - fdsconfig

-   name: setup influxdb user and group
    group: name=influxdb
    tags:
        - post-install
        - influxdb

-   user: name=influxdb
        createhome=no
        group=influxdb
    tags:
        - post-install
        - influxdb

-   name: render influxdb config
    template:
        src=../templates/deploy_fds/influxdb_config.toml.j2
        dest=/fds/etc/influxdb_config.toml
        owner=influxdb
        group=influxdb
        mode=0644
    tags:
        - post-install
        - influxdb

-   name: copy influxdb init script
    copy:
        src=../files/deploy_fds/influxdb_init.sh
        dest=/etc/init.d/influxdb
        owner=root
        group=root
        mode=0744
    tags:
        - post-install
        - init
        - influxdb

-   name: create influxdb log and data dirs
    file:
        path=/fds/var/{{item}}/influxdb
        state=directory
        owner=influxdb
        group=root
        mode=0755
    with_items:
        - logs
        - db
    tags:
        - post-install
        - influxdb

-   name: render_init_scripts
    template:
        src=../templates/deploy_fds/{{item}}-init.conf.j2
        dest=/etc/init/{{item}}.conf
        owner=root
        group=root
        mode=0644
    with_items:
        - platformd
        - orchmgr
        - amagent
        - fdsactivate
    tags:
        - post-install
        - init

-   name: render gmond config
    template: src=../templates/deploy_fds/gmond.conf.j2
        dest=/opt/fds-deps/embedded/etc/gmond.conf

-   name: start gmond service
    service: name=gmond
        state=running
