---
#######
#    When WIN-1348 is resolved, we can reinstate these tasks
#-   name: disk_type
#    shell: python -m disk_type -m
#    tags:
#      - startup
#
#-   name: start_redis
#    shell: ./redis.sh start chdir=/fds/sbin
#    tags:
#      - startup
#
#-   name: start_platformd
#    service: name=platformd state=started
#    tags:
#      - startup
#
#-   name: start_om
#    service: name=orchmgr state=started
#    when: fds_om_host is defined and fds_om_host == inventory_hostname
#    tags:
#      - startup
#
#-   name: om_wait
#    shell: sleep 8
#    when: fds_om_host is defined and fds_om_host == inventory_hostname
#    tags:
#      - startup
#
#-   name: fdsactivate
#    service: name=fdsactivate state=started
#    when: fds_om_host is defined and fds_om_host == inventory_hostname
#    tags:
#      - startup
#
#-   name: fdsactivate_wait
#    shell: sleep 8
#    when: fds_om_host is defined and fds_om_host == inventory_hostname
#    tags:
#      - startup
#
#-   name: start_am
#    service: name=amagent state=started
#    when: fds_om_host is defined and fds_om_host == inventory_hostname
#    tags:
#      - startup
#######


#######
#   When WIN-1348 is resolved, we can remove this call to fds-tool
-   name: run fds-tool.py on OM host to bring up cluster
    shell: ./fds-tool.py -f deploy_formation.conf -u
        chdir=/fds/sbin
    when: fds_om_host is defined and fds_om_host == inventory_hostname
    tags:
        - startup

-   name: check process status
    command: ./fdsadmin -f deploy_formation.conf --monitor --quiet
        chdir=/fds/sbin
    register: fdsadmin_output
    when: fds_om_host is defined and fds_om_host == inventory_hostname
    tags:
        - startup
        - status


-   debug: var=fdsadmin_output.stdout_lines
    tags:
        - startup
        - status
