---
-   name: uninstall fds-platform-(dbg|rel)
    apt: name={{item}}
        state=absent
        purge=yes
    with_items:
        - fds-platform-rel
        - fds-platform-dbg
    tags:
        - uninstall

-   name: uninstall fds-deps when installing local fds-deps package
    apt: name=fds-deps
        state=absent
        purge=yes
    when: (fds_deploy_local_deps is defined and fds_deploy_local_deps == "yes")
      and (uninstall_local_deps is defined and uninstall_local_deps == "yes")
    tags:
        - uninstall

-   name: remove_old_fdslib
    file: path=/usr/local/lib/python2.7/dist-packages/fdslib
        state=absent
    tags:
        - uninstall
