---
-   name: uninstall fds
    apt: name={{item}}
        state=absent
        purge=yes
    with_items:
        - fds-platform-rel
        - fds-platform-dbg
    tags:
        - uninstall

-   name: remove_old_fdslib
    file: path=/usr/local/lib/python2.7/dist-packages/fdslib
        state=absent
    tags:
        - uninstall
