---
local_domain_name: "{{ fds_local_domain_name if fds_local_domain_name is defined else 'local' }}"

activate_local_domain_post_body:
    action: "activate"
    am: "true"
    dm: "true"
    sm: "true"

activate_local_domain_post_body_json: "{{ activate_local_domain_post_body | to_json }}"

activate_node_services_post_body:
    am: "true"
    dm: "false"
    sm: "true"

activate_node_services_post_body_json: "{{ activate_node_services_post_body | to_json }}"

shutdown_domain_put_body:
    id: "1"
    name: "local"
    site: "local"
    state: "DOWN"

shutdown_domain_put_body_json: "{{ shutdown_domain_put_body | to_json }}"
