---
-   name: Provision 4-node FDS cluster in EC2
    connection: local
    hosts: localhost
    gather_facts: False

    tasks:

    -   name: check for instance_name_tag
        fail: msg="You must supply a value for instance_name_tag"
        when: instance_name_tag is not defined

    -   name: check for instance_count
        fail: msg="You must supply a value for instance_count"
        when: instance_count is not defined

    -   name: spin up a node in the private subnet with an auto-assigned IP
        ec2:
            instance_tags:
                Name: "{{ instance_name_tag }}"
                fds_purpose: testing
            exact_count: "{{ instance_count }}"
            count_tag:
                Name: "{{ instance_name_tag }}"
                fds_purpose: testing
            key_name: fds-ie
            group_id: sg-43b9c126
            instance_type: t2.micro
            image: ami-13e3b223
            volumes:
                -   device_name: /dev/sda1
                    volume_size: 20
                    delete_on_termination: true
            vpc_subnet_id: subnet-195bac40
            monitoring: no
            region: us-west-2
            zone: us-west-2c
            wait: yes
        register: ec2

    -   name: Add all instance public IPs to host group
        add_host: hostname={{ item.private_ip }} groupname=ec2hosts
        with_items: ec2.tagged_instances

    -   name: wait for SSH to come up on all instances
        local_action: wait_for host={{ item.private_ip }} port=22 delay=1 timeout=300 state=started
        with_items: ec2.tagged_instances

-   hosts: ec2hosts
    name: configuration play
    user: deploy
    gather_facts: true
    sudo: true
    vars:
        this_is_an_ec2_node: true

    handlers:
    -   name: restart ssh
        service: name=ssh
            state=restarted

    tasks:

    -   include: ../tasks/deploy_fds/pre_deploy_setup.yml

    -   include: ../tasks/deploy_fds/install_deps.yml

    -   include: ../tasks/deploy_fds/add_fds_repos.yml


