---
-   name: Provision 4-node FDS cluster in EC2
    connection: local
    hosts: localhost
    gather_facts: False

    tasks:

    -   name: check for instance_name_tag
        fail: msg="You must supply a value for instance_name_tag"
        when: instance_name_tag is not defined

    -   name: check for instance_count
        fail: msg="You must supply a value for instance_count"
        when: instance_count is not defined

    -   name: spin up a node in the private subnet with an auto-assigned IP
        ec2:
            instance_tags:
                Name: "{{ instance_name_tag }}"
                fds_purpose: testing
            exact_count: "{{ instance_count }}"
            count_tag:
                Name: "{{ instance_name_tag }}"
                fds_purpose: testing
            key_name: fds-ie
            group_id: sg-43b9c126
            instance_type: t2.micro
            image: ami-f90556c9
            volumes:
                -   device_name: /dev/sda1
                    volume_size: 30
                    delete_on_termination: true
            vpc_subnet_id: subnet-195bac40
            monitoring: no
            region: us-west-2
            zone: us-west-2c
            wait: yes
        register: ec2

    -   name: Add all instance public IPs to host group
        add_host: hostname={{ item.private_ip }} groupname=ec2hosts
        with_items: ec2.tagged_instances

################################################################################
### This is necessary for now until I can get a Github issue put in and resolved
-   hosts: awo-bh-01
    name: wait for EC2 instances to be reachable
    remote_user: deploy
    gather_facts: false
    sudo: false
    tags: wait

    tasks:

    -   name: wait for SSH to come up on all instances
        wait_for: host={{ item }} port=22 delay=1 timeout=300 state=started
        with_items: groups.ec2hosts
################################################################################


-   name: DESTRUCTIVE Deployment of FDS
    hosts: ec2hosts
    remote_user: deploy
    gather_facts: true
    sudo: true
    vars:
        this_is_an_ec2_node: true

    handlers:
    -   name: restart ssh
        service: name=ssh
            state=restarted

    tasks:

#    -   include: ../tasks/deploy_fds/pre_deploy_setup.yml

#    -   include: ../tasks/deploy_fds/stop_and_clean_fds.yml

#    -   include: ../tasks/deploy_fds/install_deps.yml

#    -   include: ../tasks/deploy_fds/uninstall_fds.yml

#    -   include: ../tasks/deploy_fds/install_fds.yml

    -   include: ../tasks/deploy_fds/set_node_num.yml

    -   include: ../tasks/deploy_fds/post_install_setup.yml

#    -   include: ../tasks/deploy_fds/start_fds.yml
