---
-   name: Provision 4-node FDS cluster in EC2
    connection: local
    hosts: localhost
    gather_facts: False
    vars_files:
    -   ../vars_files/multi_om_setup.yml
    -   ../vars_files/credentials/aws_fds_testing.yml
    -   ../vars_files/credentials/fds-deploy_rsa.yml

    tasks:

    -   name: check for instance_name_tag
        fail: msg="You must supply a value for instance_name_tag"
        when: instance_name_tag is not defined

    -   name: check for instance_count
        fail: msg="You must supply a value for instance_count"
        when: instance_count is not defined

    -   name: copy FDS deploy key locally
        include: ../tasks/deploy_fds/copy_fds_deploy_key.yml

    -   name: spin up a node in the private subnet with an auto-assigned IP
        ec2:
            aws_access_key: "{{ aws_access_key }}"
            aws_secret_key: "{{ aws_secret_key }}"
            instance_tags:
                Name: "{{ instance_name_tag }}"
                fds_purpose: testing
            exact_count: "{{ instance_count }}"
            count_tag:
                Name: "{{ instance_name_tag }}"
                fds_purpose: testing
            key_name: fds-ie
            group_id: sg-43b9c126
            instance_type: t2.micro
            image: ami-fb5506cb
            volumes:
                -   device_name: /dev/sda1
                    volume_size: 30
                    delete_on_termination: true
            vpc_subnet_id: subnet-195bac40
            monitoring: no
            region: us-west-2
            zone: us-west-2c
            wait: yes
        register: ec2

    -   name: Add all instance public IPs to host group
        add_host: hostname={{ item.private_ip }} groupname=ec2hosts
        with_items: ec2.tagged_instances

################################################################################
### This is necessary for now until I can get a Github issue put in and resolved
-   hosts: awo-bh-01
    name: wait for EC2 instances to be reachable
    remote_user: deploy
    gather_facts: false
    sudo: false
    tags: wait

    tasks:

    -   name: wait for SSH to come up on all instances
        wait_for: host={{ item }} port=22 delay=1 timeout=300 state=started
        with_items: groups.ec2hosts
################################################################################


-   name: Deploy FDS
    hosts: ec2hosts
    remote_user: deploy
    gather_facts: true
    sudo: true
    vars:
        this_is_an_ec2_node: true

    handlers:
    -   name: restart ssh
        service: name=ssh
            state=restarted

    tasks:

    -   include: ../tasks/deploy_fds/deploy_fds.yml
