---
-   name: deploy rendered FDS config files without code
    hosts: all
    sudo: yes
    vars_files:
        - ../vars_files/multi_om_setup.yml

    tasks:
    -   include: ../tasks/deploy_fds/config_sanity_check.yml

    -   name: create safe directory for configs to be dumped to
        file: path=/root/fds_configs
            state=directory
            owner=root
            group=root
            mode=755

    -   name: render common configs
        template:
            src: ../../source/config/etc/{{item}}.conf.j2
            dest: /root/fds_configs/{{item}}.conf
        with_items:
            - fds
            - platform
            - redis

    -   name: render formation.conf
        template:
            src: ../../source/test/formation.conf.j2
            dest: /root/fds_configs/formation.conf
