---

-   name: Setup ssh key
    hosts: all
    gather_facts: no
    sudo: no
    vars_files:
        - ../vars_files/credentials/fds-deploy_rsa.yml
    tags:
        - pre_deploy

    tasks:
    -   include: ../tasks/deploy_fds/copy_fds_deploy_key.yml

-   name: Pre-Deploy - check sudo privileges
    hosts: all
    gather_facts: no
    sudo: no
    vars_files:
        - ../vars_files/credentials/fds-deploy_rsa.yml
    tags:
        - check_sudo

    tasks:
    -   include: ../tasks/common/check_sudo.yml
        when: ansible_sudo_pass is not defined

-   name: Pre-Deploy - setup environment
    hosts: all
    gather_facts: no
    sudo: yes
    tags:
        - pre_deploy

    handlers:
    -   name: restart ssh
        service: name=ssh
            state=restarted

    tasks:
    -   include: ../tasks/deploy_fds/pre_deploy_setup.yml


-   name: Deploy FDS
    hosts: all
    gather_facts: yes
    sudo: yes
    vars_files:
    -   ../vars_files/credentials/ssl_certs.yml
    -   ../vars_files/multi_om_setup.yml
    -   ../vars_files/deploy_fds/start_fds.yml
    -   ../vars_files/deploy_fds/admin_credentials.yml

    tasks:
    -   include: ../tasks/deploy_fds/deploy_fds.yml
