---
-   name: install needed packages for devsetup
    hosts: localhost
    vars:
        - influxdb_version: 0.8.8

    tasks:

    - name: create /corefiles directory
      file: path=/corefiles
        state=directory
        owner=root
        group=root
        mode=0777
      sudo: yes

    - name: set sysctl config
      sysctl: name={{item.key}} value={{item.value.value}} state={{item.value.state}}
      with_dict:
        kernel.core_pattern:
            value: /corefiles/%e-%p-%u-%t.core
            state: present
        fs.file-max:
            value: 400000
            state: present
        kernel.core_uses_pid:
            value: 1
            state: present
        fs.suid_dumpable:
            value: 1
            state: present
      sudo: yes

    - name: install_limits_conf
      template:
        src=../templates/deploy_fds/fds_limits.conf
        dest=/etc/security/limits.conf
        owner=root
        group=root
        mode=0644
      sudo: yes

    - name: Copy sudoers for safety
      command: cp -f /etc/sudoers /etc/sudoers.tmp
      sudo: yes

    - name: Backup sudoers
      command: cp -f /etc/sudoers /etc/sudoers.bak
      sudo: yes

    - name: Make sure we retain BUILD_ID for Jenkins
      lineinfile:
        dest=/etc/sudoers.tmp
        state=present
        insertafter='^Defaults'
        regexp='^Defaults env_keep\+\=BUILD_ID'
        line='Defaults env_keep+=BUILD_ID'
      sudo: yes

    - name: Sudoers syntax check && replace
      shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers
      sudo: yes

    - name: Cleanup tmp sudoers
      command: rm -f /etc/sudoers.tmp
      sudo: yes

    - name: remove JRE ppa
      apt_repository: repo=ppa:webupd8team/java state=absent
      sudo: yes
      ignore_errors: yes

    - name: add artifactory repo key
      apt_key: url="http://builder:h7qgA3fYr0P3@artifacts.artifactoryonline.com/artifacts/api/gpg/key/public"
      sudo: yes

    - name: add fds repo
      apt_repository: repo="deb http://builder:h7qgA3fYr0P3@artifacts.artifactoryonline.com/artifacts/third-party-deps/ fds main" state=present
      sudo: yes

    - name: add fds nightly repo
      apt_repository: repo="deb http://builder:h7qgA3fYr0P3@artifacts.artifactoryonline.com/artifacts/formation-apt/ platform nightly" state=present
      sudo: yes

    - name: automatically select the oracle license
      shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
      sudo: yes

    - name: purge redis packages
      apt: name={{item}} force=yes state=absent update_cache=no
      with_items:
        - redis-server
        - redis-tools
      sudo: yes

    - name: purge libboost 1.54 packages
      apt: name={{item}} force=yes state=absent update_cache=no
      with_items:
        - libboost1.54-dev
        - libboost-log1.54-dev
        - libboost-program-options1.54-dev
        - libboost-timer1.54-dev
        - libboost-thread1.54-dev
        - libboost-regex1.54-dev
        - libboost-chrono1.54-dev
        - libboost1.54
        - libboost-log1.54
        - libboost-program-options1.54
        - libboost-timer1.54
        - libboost-thread1.54
        - libboost-regex1.54
        - libboost-chrono1.54
      sudo: yes

    - name: install latest fds-deps package
      apt: name=fds-deps force=yes state=latest update_cache=yes cache_valid_time=600
      sudo: yes

    - name: install latest fds-stats-deps package
      apt: name=fds-stats-deps force=yes state=latest update_cache=yes cache_valid_time=600
      sudo: yes

    - name: install latest fds-stats-service package
      apt: name=fds-stats-service-2.0.0 force=yes state=latest update_cache=yes cache_valid_time=600
      sudo: yes

    - name: install latest rabbitmq-c package
      apt: name=rabbitmq-c-0.7.1 force=yes state=latest update_cache=yes cache_valid_time=600
      sudo: yes

    - name: install latest simple amqp client package
      apt: name=simpleamqpclient-0.7.1 force=yes state=latest update_cache=yes cache_valid_time=600
      sudo: yes

    - name: install latest fds-stats-client-c package
      apt: name=fds-stats-client-c-2.0.0 force=yes state=latest update_cache=yes cache_valid_time=600
      sudo: yes

    - name: install fds-stats-util package
      apt: name=fds-stats-util=1.0.0 force=yes state=present update_cache=yes cache_valid_time=600
      sudo: yes

    - name: remove latest java package
      apt: name=oracle-java8-installer force=yes state=latest update_cache=yes cache_valid_time=600
      sudo: yes
      ignore_errors: yes

    - name: download java JDK
      get_url: url=http://bld-artifactory.formationds.com:8081/artifactory/list/external_packages/server-jre-8u60-linux-x64.tar.gz dest=/tmp
      sudo: yes

    - name: unarchive java JDK
      unarchive: copy=no src=/tmp/server-jre-8u60-linux-x64.tar.gz dest=/opt
      sudo: yes

#    - name: install versioned os packages
#      apt: name={{ item.key }} version={{ item.value.version }} force=yes state=present update_cache=yes cache_valid_time=600
#      with_dict:
#        libjemalloc:
#            version: 3.5.1-2
#

    - name: install os packages
      apt: name={{item}} force=yes state=present update_cache=yes cache_valid_time=600
      with_items:
        - automake
        - binutils-dev
        - cmake
        - cpanminus
        - git
        - libapr1-dev
        - libconfuse-dev
        - libxml2-dev
        - libxslt1-dev
        - linux-generic
        - linux-headers-generic
        - linux-image-generic
        - libcurl4-openssl-dev
        - python3-distupgrade
        - ubuntu-release-upgrader-core
        - gdb
        - build-essential
        - python-software-properties
        - software-properties-common
        - maven
        - libudev-dev
        - libparted0-dev
        - python2.7
        - python-dev
        - python-setuptools
        - libpcre3-dev
        - libpcre3
        - libssl-dev
        - libfuse-dev
        - libevent-dev
        - libev-dev
        - libfiu-dev
        - "libjemalloc1=3.5.1-2"
        - "libjemalloc-dev=3.5.1-2"
        - libtool
        - fiu-utils
        - bison
        - flex
        - ragel
        - ccache
        - libboost1.55-dev
        - libboost-log1.55-dev
        - libboost-program-options1.55-dev
        - libboost-timer1.55-dev
        - libboost-thread1.55-dev
        - libboost-test1.55-dev
        - libboost-regex1.55-dev
        - libboost-filesystem1.55-dev
        - libboost-chrono1.55-dev
        - libical-dev
        - libical1
        - libleveldb-dev
        - google-perftools
        - libgoogle-perftools-dev
        - libconfig++-dev
        - libcurl4-openssl-dev
        - libcpr-1.2.0
        - npm
        - nodejs-legacy
        - open-iscsi
        - ruby1.9.1-full
        - ruby-sass
        - python-concurrent.futures
        - python-paramiko
        - python-redis
        - python-requests
        - python-argh
        - python-boto
        - python-thrift
        - libncurses5-dev
        - lintian
        - libhiredis0.10
        - libhiredis-dev
        - libsqlite3-dev
        - sg3-utils
        - scsitools
        - swig3.0
        - sshpass
        - nbd-client
        - fio
        - python-coverage-test-runner
        - python-mock
        - valgrind
      sudo: yes

    - name: Install libnfs and libnfs-python for NFS IO
      command: bash ../scripts/install_libnfs.sh

    - name: touch pip config file at ~/pip/pip.conf
      file: path="{{ lookup('env','HOME') }}/.pip/pip.conf"
        state=absent

    - name: create pip config directory at ~/.pip
      file: path="{{ lookup('env','HOME') }}/.pip"
        state=absent

    - name: install pip packages
      pip: name={{item}}
        state=present
      sudo: yes
      with_items:
        - scp
        - PyYAML
        - xmlrunner
        - filechunkio
        - httplib2
        - docker-py
        - psutil
        - fstab
        - pyudev
        - "PyInstaller==3.1"
        - "tabulate==0.7.4"
        - "urllib3==1.10.1"
        - python-iptables
        - retry
        - retrying
        - humanize
        - numpy

    - name: install Formation pip packages
      pip: name={{item}}
        state=present
        extra_args="--extra-index-url=https://builder:h7qgA3fYr0P3@artifacts.artifactoryonline.com/artifacts/api/pypi/formation-pip/simple -I"
      sudo: yes
      with_items:
        - "pyscsi-linux==1.0"
        - "fdscli==0.1.21"

    - name: install perl modules
      cpanm: name={{ item }} mirror=http://cpan.mirror.vexxhost.com notest=true
      with_items:
        - JSON

    - name: install ruby gems
      gem: name={{ item }} state=present user_install=no
      with_items:
        - bundler

    - name: create java home script
      copy: src=../files/jdk.sh dest=/etc/profile.d/jdk.sh owner=root group=root mode=0755
      sudo: yes

    - name: source java home
      shell: . /etc/profile.d/jdk.sh

    - name: update_java_alternatives
      alternatives: name=java path=/opt/jdk1.8.0_60/bin/java
      sudo: yes

    - name: create omnibus install directory for fds-platform
      file: path=/fds
        owner=root
        mode=0777
        state=directory
      sudo: yes

    - name: create omnibus install directory for fds-deps
      file: path=/opt/fds-deps
        owner=root
        mode=0777
        state=directory
      sudo: yes

    - name: create omnibus install directory for fds-deploy
      file: path=/opt/fds-deploy
        owner=root
        mode=0777
        state=directory
      sudo: yes

    - name: get InfluxDB package
      get_url: url=https://s3.amazonaws.com/influxdb/influxdb_{{ influxdb_version }}_amd64.deb
           dest=/opt/influxdb_{{ influxdb_version }}_amd64.deb
           validate_certs=no
           sha256sum=04f0b74ca102e2680191bbd83aa2601cd7ce1b50b3fd8aa7d7d084fa7032c492
      sudo: yes

    - name: create influxdb user and group
      group: name=influxdb
      sudo: yes

    - user: name=influxdb
        createhome=no
        group=influxdb
      sudo: yes

    - name: install InfluxDB
      apt: deb=/opt/influxdb_{{ influxdb_version }}_amd64.deb
      register: install
      sudo: yes

    - name: set local for error messages
      command: update-locale LC_MESSAGES=POSIX
      sudo: yes
