---
-   name: install needed packages for devsetup
    hosts: localhost
    sudo: yes

    tasks:

    - name: add JRE ppa
      apt_repository: repo=ppa:webupd8team/java state=present

    - name: add redis-server ppa
      apt_repository: repo=ppa:chris-lea/redis-server state=present

    - name: add fds repo
      apt_repository: repo='deb http://coke.formationds.com:8000 fds test' state=present

    - name: automatically select the oracle license
      shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

    - name: purge libboost 1.54 packages
      apt: name={{item}} force=yes state=absent update_cache=no
      with_items:
        - libboost1.54-dev
        - libboost-log1.54-dev
        - libboost-program-options1.54-dev
        - libboost-timer1.54-dev
        - libboost-thread1.54-dev
        - libboost-regex1.54-dev
        - libboost1.54
        - libboost-log1.54
        - libboost-program-options1.54
        - libboost-timer1.54
        - libboost-thread1.54
        - libboost-regex1.54

    - name: install os packages
      apt: name={{item}} force=yes state=present update_cache=yes cache_valid_time=600
      with_items:
        - automake
        - cmake
        - cpanminus
        - git
        - linux-generic
        - linux-headers-generic
        - linux-image-generic
        - libcurl4-openssl-dev
        - python3-distupgrade
        - ubuntu-release-upgrader-core
        - gdb
        - build-essential
        - python-software-properties
        - software-properties-common
        - redis-server
        - redis-tools
        - maven
        - libudev-dev
        - libparted0-dev
        - python2.7
        - python-dev
        - python-pip
        - python-boto
        - libpcre3-dev
        - libpcre3
        - libssl-dev
        - libfuse-dev
        - libevent-dev
        - libev-dev
        - libfiu-dev
        - libtool
        - fiu-utils
        - bison
        - flex
        - ragel
        - ccache
        - libboost1.55-dev
        - libboost-log1.55-dev
        - libboost-program-options1.55-dev
        - libboost-timer1.55-dev
        - libboost-thread1.55-dev
        - libboost-regex1.55-dev
        - libboost-filesystem1.55-dev
        - libical-dev
        - libical1
        - libjemalloc-dev
        - libleveldb-dev
        - google-perftools
        - libgoogle-perftools-dev
        - libconfig++-dev
        - oracle-java8-installer
        - npm
        - nodejs-legacy
        - ruby1.9.1-full
        - ruby-sass
        - python-concurrent.futures
        - python-paramiko
        - python-redis
        - python-requests
        - python-boto
        - python-argh
        - python-thrift
        - fds-pkghelper
        - fds-pkg
        - fds-pkgtools=0.3.2
        - fds-systemdir
        - fds-coredump
        - libcryptopp-dev
        - lintian
        - libhiredis0.10
        - libhiredis-dev
        - libsqlite3-dev
        - swig3.0
        - sshpass
        - nbd-client
        - fio

    - name: install pip packages
      pip: name={{item}} state=present
      with_items:
        - scp
        - PyYAML
        - tabulate
        - xmlrunner
        - filechunkio
        - httplib2
        - docker-py
        - psutil

    - name: install perl modules
      cpanm: name={{ item }} mirror=http://cpan.mirror.vexxhost.com notest=true
      with_items:
        - JSON

    - name: install ruby gems
      gem: name={{ item }} state=present user_install=no
      with_items:
        - bundler

    - name: create java home script
      copy: src=../files/jdk.sh dest=/etc/profile.d/jdk.sh owner=root group=root mode=0755

    - name: update_java_alternatives
      alternatives: name=java path=/usr/lib/jvm/java-8-oracle/jre/bin/java
