---

-   name: install and configure fds on all  fds_nodes
    hosts: local-fds-nodes
    remote_user: vagrant
    sudo: True

    handlers:
    -   name: restart ssh
        service: name=ssh state=restarted

    tasks:
    -   name: copy fdsinstall tarball
        copy: 
            src=../resources/fdsinstall.tgz 
            dest=/root/fdsinstall.tgz 
            owner=root 
            group=root 
            mode=0644

    -   name: extract fdsinstall tarball
        unarchive: 
            creates=/root/fdsinstall 
            src=/root/fdsinstall.tgz 
            dest=/root 
            copy=no

    -   name: run fdsinstall step 2 - install external pkgs
        shell: ./fdsinstall.py -o 5 -o 2  && touch /root/.fdsinstall_step2_ran 
            chdir=/root/fdsinstall 
            creates=/root/.fdsinstall_step2_ran

    -   name: run fdsinstall step 3 - setup storage
        shell: ./fdsinstall.py -o 5 -o 3  && touch /root/.fdsinstall_step3_ran 
            chdir=/root/fdsinstall 
            creates=/root/.fdsinstall_step3_ran

    -   name: run fdsinstall step 4 - install FDS pkgs
        shell: ./fdsinstall.py -o 5 -o 4  && touch /root/.fdsinstall_step4_ran 
            chdir=/root/fdsinstall 
            creates=/root/.fdsinstall_step4_ran

    -   name: render formation.conf
        template: 
            src=../../source/test/formation.conf.j2 
            dest=/fds/sbin/formation.conf 
            owner=root 
            group=root 
            mode=0644

    -   name: render /fds/etc config files
        template: 
            src=../../source/config/etc/{{item}}.conf.j2 
            dest=/fds/etc/{{item}}.conf 
            owner=root 
            group=root 
            mode=0644
        with_items:
            - fds
            - fds-features
            - platform
            - orch_mgr
            - redis

    -   name: allow ssh root login
        command: sed -ie 's/PermitRootLogin without-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
        notify: restart ssh


-   name: start FDS from first node
    hosts: node0
    remote_user: vagrant 
    sudo: True

    tasks:
    -   name: attempt to start FDS
        command: ./fds-tool.py -f formation.conf -u 
            chdir=/fds/sbin

    -   name: check process status
        command: ./fdsadmin --process-status 
            chdir=/fds/sbin
        register: fdsadmin_output
        tags:
            -   dbg
    -   debug: var=fdsadmin_output.stdout_lines
