---

-   name: Install Logstash
    hosts: logstash-nodes
    gather_facts: yes
    sudo: yes

    tasks:

    -   name: add logstash repo key
        apt_key: url="http://packages.elasticsearch.org/GPG-KEY-elasticsearch"

    -   name: add logstash repo config
        apt_repository: repo="deb http://packages.elasticsearch.org/logstash/1.4/debian stable main"
            state=present

    -   name: install logstash
        apt: name=logstash
            force=yes
            update_cache=yes
