---
-   name: math experiments
    hosts: all
    gather_facts: true
    sudo: true
    vars:
        ansible_ssh_user: ubuntu
        ansible_ssh_pass: ubuntu
        ansible_ssh_sudo: ubuntu
        empty_om_list: "configure_via_the_inventory_file"
        hosts_in_group: "{{ groups[group_names[0]] | length }}"
        om_ip_count: "{{ fds_om_host_count if fds_om_host_count is defined and fds_ft_common_enable_multi_om_support is defined and fds_ft_common_enable_multi_om_support == 'true' else empty_om_list }}"

    tasks:

    -   name: "sanity check -> fds_om_host_count is defined when fds_ft_common_enable_multi_om_support==true"
        fail: msg="You must specify a value for fds_om_host_count (odd integer >= 3) when fds_ft_common_enable_multi_om_support == true"
        when: om_ip_count == empty_om_list and fds_ft_common_enable_multi_om_support is defined and fds_ft_common_enable_multi_om_support == 'true'

    -   name: sanity check -> fds_om_host_count <= hosts count
        fail: msg="You've specified more OM hosts than there are hosts in the group. Exiting."
        when: om_ip_count != empty_om_list and om_ip_count|int > hosts_in_group|int

    -   name: sanity check -> fds_om_host_count is >= 3
        fail: msg="You've specified an invalid fds_om_host_count value for use with fds_ft_common_enable_multi_om_support=true. Value must be an odd integer >= 3"
        when: om_ip_count != empty_om_list and (om_ip_count|int < 3 or om_ip_count|int is divisibleby 2)

    -   name: host count
        debug:
            msg: "{{hosts_in_group}}"

    -   name: om ip count
        debug:
            msg: "{{om_ip_count}}"

    -   template:
            src=../../source/config/etc/platform.conf.j2
            dest=/root/platform.conf
            owner=root
            mode=0644
