# vim: set tabstop=2 expandtabs
---

-   name: Setup python
    hosts: all
    gather_facts: no
    remote_user: ubuntu
    sudo: True

    tasks:

    -   name: get some python on it
        raw: apt-get -y install python

-   name: Setup any pre-requisities on host
    hosts: all
    sudo: True

    handlers:
    -   name: restart ssh
        service: name=ssh 
            state=restarted

    tasks:

    -   name: set the root password
        action: user name=root
            password=passwd

    -   name: allow ssh root login
        lineinfile: dest=/etc/ssh/sshd_config 
            regexp="PermitRootLogin without-password" 
            line="PermitRootLogin yes" 
            backrefs=yes
            state=present
        notify: restart ssh
