# vim: set tabstop=2 expandtabs
---

-   name: Setup python
    hosts: all
    gather_facts: no
    remote_user: ubuntu
    sudo: True

    tasks:

    -   name: get some python on it
        raw: apt-get -y install python

-   name: Setup any pre-requisities on host
    hosts: all

    handlers:
    -   name: restart ssh
        service: name=ssh state=restarted

    tasks:

    -   name: set the root password
        raw: echo "root:passwd" | chpasswd

    -   name: allow ssh root login
        command: sed -ie 's/PermitRootLogin without-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
        notify: restart ssh
