---
-   name: Provision 4-node FDS cluster in EC2
    connection: local
    hosts: localhost
    gather_facts: False

    tasks:

    -   name: spin up a node in the private subnet with an auto-assigned IP
        ec2:
            instance_tags:
                Name: codytest
                fds_purpose: testing
            exact_count: 4
            count_tag:
                Name: codytest
                fds_purpose: testing
            key_name: fds-ie
            group_id: sg-43b9c126
            instance_type: t2.micro
            image: ami-13e3b223
            volumes:
                -   device_name: /dev/sda1
                    volume_size: 20
                    delete_on_termination: true
            vpc_subnet_id: subnet-195bac40
            monitoring: no
            region: us-west-2
            zone: us-west-2c
            wait: yes
        register: ec2

    -   name: Add all instance public IPs to host group
        add_host: hostname={{ item.private_ip }} groupname=ec2hosts
        with_items: ec2.tagged_instances

-   hosts: ec2hosts
    name: configuration play
    user: deploy
    gather_facts: false

    tasks:

    -   name: wait for SSH to come up on all instances
        wait_for: host={{ inventory_hostname }} port=22 delay=1 timeout=320 state=started

-   hosts: ec2hosts
    name: configuration play
    user: deploy
    gather_facts: true

    tasks:
    -   debug: msg={{ fds_om_host }}
