---
ec2_hosts:
   node1:
      address: 10.3.20.31
      hostname: "node1"
   node2:
      address: 10.3.20.32
      hostname: "node2"
   node3:
      address: 10.3.20.33
      hostname: "node3"
   node4:
      address: 10.3.20.34
      hostname: "node4"
