---
ec2_hosts:
   node1:
      address: 10.3.20.40
      hostname: "node1"
   node2:
      address: 10.3.20.41
      hostname: "node2"
   node3:
      address: 10.3.20.42
      hostname: "node3"
   node4:
      address: 10.3.20.43
      hostname: "node4"
   node5:
      address: 10.3.20.44
      hostname: "node5"
   node6:
      address: 10.3.20.45
      hostname: "node6"
   node7:
      address: 10.3.20.46
      hostname: "node7"
   node8:
      address: 10.3.20.47
      hostname: "node8"
   node9:
      address: 10.3.20.48
      hostname: "node9"
   node10:
      address: 10.3.20.49
      hostname: "node10"
   node11:
      address: 10.3.20.50
      hostname: "node11"
   node12:
      address: 10.3.20.51
      hostname: "node12"
   node13:
      address: 10.3.20.52
      hostname: "node13"
   node14:
      address: 10.3.20.53
      hostname: "node14"
   node15:
      address: 10.3.20.54
      hostname: "node15"
   node16:
      address: 10.3.20.55
      hostname: "node16"
